# Configuração Dinâmica da Base de Dados (fallback para H2 local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:devshowcasedb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# Hibernate & JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Porta Dinâmica para o Render
server.port=${PORT:8080}